In [2]:
import pandas as pd

In [9]:
series = pd.read_csv(
    "../data/food_prices_series_raw.csv",
    encoding="latin1"
)

series.head()

,Classification Name,Classification Code,Country Name,Country Code,Time,Time Code,Cost of an energy sufficient diet [CoCA],Cost of a nutrient adequate diet [CoNA],Cost of a healthy diet [CoHD],Cost of a healthy diet relative to the cost of sufficient energy from starchy staples [CoHD_CoCA],...,Affordability of an energy sufficient diet: ratio of cost to food expenditures [CoCA_fexp],Affordability of a nutrient adequate diet: ratio of cost to food expenditures [CoNA_fexp],Affordability of a healthy diet: ratio of cost to food expenditures [CoHD_fexp],Percent of the population who cannot afford sufficient calories [CoCA_headcount],Percent of the population who cannot afford nutrient adequacy [CoNA_headcount],Percent of the population who cannot afford a healthy diet [CoHD_headcount],Millions of people who cannot afford sufficient calories [CoCA_unafford_n],Millions of people who cannot afford nutrient adequacy [CoNA_unafford_n],Millions of people who cannot afford a healthy diet [CoHD_unafford_n],Population [Pop]
0,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2017.0,YR2017,0.604,1.88,3.476,5.75,...,0.111,0.346,0.64,0,3.2,21.8,0,0.4,2.5,11433438
1,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2018.0,YR2018,..,..,3.559,..,...,..,..,..,..,..,21.2,..,..,2.5,11565203
2,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2019.0,YR2019,..,..,3.628,..,...,..,..,..,..,..,20.8,..,..,2.4,11694721
3,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2020.0,YR2020,..,..,3.639,..,...,..,..,..,..,..,20.3,..,..,2.4,11818618
4,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2021.0,YR2021,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..

In [10]:
series.to_csv(
    "../data/food_prices_series_utf8.csv",
    index=False,
    encoding="utf-8"
)

In [11]:
series_utf8 = pd.read_csv("../data/food_prices_series_utf8.csv")
series_utf8.head()

,Classification Name,Classification Code,Country Name,Country Code,Time,Time Code,Cost of an energy sufficient diet [CoCA],Cost of a nutrient adequate diet [CoNA],Cost of a healthy diet [CoHD],Cost of a healthy diet relative to the cost of sufficient energy from starchy staples [CoHD_CoCA],...,Affordability of an energy sufficient diet: ratio of cost to food expenditures [CoCA_fexp],Affordability of a nutrient adequate diet: ratio of cost to food expenditures [CoNA_fexp],Affordability of a healthy diet: ratio of cost to food expenditures [CoHD_fexp],Percent of the population who cannot afford sufficient calories [CoCA_headcount],Percent of the population who cannot afford nutrient adequacy [CoNA_headcount],Percent of the population who cannot afford a healthy diet [CoHD_headcount],Millions of people who cannot afford sufficient calories [CoCA_unafford_n],Millions of people who cannot afford nutrient adequacy [CoNA_unafford_n],Millions of people who cannot afford a healthy diet [CoHD_unafford_n],Population [Pop]
0,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2017.0,YR2017,0.604,1.88,3.476,5.75,...,0.111,0.346,0.64,0,3.2,21.8,0,0.4,2.5,11433438
1,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2018.0,YR2018,..,..,3.559,..,...,..,..,..,..,..,21.2,..,..,2.5,11565203
2,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2019.0,YR2019,..,..,3.628,..,...,..,..,..,..,..,20.8,..,..,2.4,11694721
3,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2020.0,YR2020,..,..,3.639,..,...,..,..,..,..,..,20.3,..,..,2.4,11818618
4,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2021.0,YR2021,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..

In [13]:
data = pd.read_csv(
    "../data/food_prices_data_raw.csv",
    encoding="latin1"
)

data.head()

,Classification Name,Classification Code,Country Name,Country Code,Time,Time Code,Cost of an energy sufficient diet [CoCA],Cost of a nutrient adequate diet [CoNA],Cost of a healthy diet [CoHD],Cost of a healthy diet relative to the cost of sufficient energy from starchy staples [CoHD_CoCA],...,Affordability of an energy sufficient diet: ratio of cost to food expenditures [CoCA_fexp],Affordability of a nutrient adequate diet: ratio of cost to food expenditures [CoNA_fexp],Affordability of a healthy diet: ratio of cost to food expenditures [CoHD_fexp],Percent of the population who cannot afford sufficient calories [CoCA_headcount],Percent of the population who cannot afford nutrient adequacy [CoNA_headcount],Percent of the population who cannot afford a healthy diet [CoHD_headcount],Millions of people who cannot afford sufficient calories [CoCA_unafford_n],Millions of people who cannot afford nutrient adequacy [CoNA_unafford_n],Millions of people who cannot afford a healthy diet [CoHD_unafford_n],Population [Pop]
0,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2017.0,YR2017,0.604,1.88,3.476,5.75,...,0.111,0.346,0.64,0,3.2,21.8,0,0.4,2.5,11433438
1,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2018.0,YR2018,..,..,3.559,..,...,..,..,..,..,..,21.2,..,..,2.5,11565203
2,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2019.0,YR2019,..,..,3.628,..,...,..,..,..,..,..,20.8,..,..,2.4,11694721
3,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2020.0,YR2020,..,..,3.639,..,...,..,..,..,..,..,20.3,..,..,2.4,11818618
4,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2021.0,YR2021,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..

In [14]:
data.to_csv(
    "../data/food_prices_data_utf8.csv",
    index=False,
    encoding="utf-8"
)

In [15]:
data_utf8 = pd.read_csv("../data/food_prices_data_utf8.csv")
data_utf8.head()

,Classification Name,Classification Code,Country Name,Country Code,Time,Time Code,Cost of an energy sufficient diet [CoCA],Cost of a nutrient adequate diet [CoNA],Cost of a healthy diet [CoHD],Cost of a healthy diet relative to the cost of sufficient energy from starchy staples [CoHD_CoCA],...,Affordability of an energy sufficient diet: ratio of cost to food expenditures [CoCA_fexp],Affordability of a nutrient adequate diet: ratio of cost to food expenditures [CoNA_fexp],Affordability of a healthy diet: ratio of cost to food expenditures [CoHD_fexp],Percent of the population who cannot afford sufficient calories [CoCA_headcount],Percent of the population who cannot afford nutrient adequacy [CoNA_headcount],Percent of the population who cannot afford a healthy diet [CoHD_headcount],Millions of people who cannot afford sufficient calories [CoCA_unafford_n],Millions of people who cannot afford nutrient adequacy [CoNA_unafford_n],Millions of people who cannot afford a healthy diet [CoHD_unafford_n],Population [Pop]
0,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2017.0,YR2017,0.604,1.88,3.476,5.75,...,0.111,0.346,0.64,0,3.2,21.8,0,0.4,2.5,11433438
1,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2018.0,YR2018,..,..,3.559,..,...,..,..,..,..,..,21.2,..,..,2.5,11565203
2,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2019.0,YR2019,..,..,3.628,..,...,..,..,..,..,..,20.8,..,..,2.4,11694721
3,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2020.0,YR2020,..,..,3.639,..,...,..,..,..,..,..,20.3,..,..,2.4,11818618
4,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2021.0,YR2021,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..

In [16]:
print(data.shape)
display(data.head())

print(series.shape)
display(series.head())

(3725, 40)

,Classification Name,Classification Code,Country Name,Country Code,Time,Time Code,Cost of an energy sufficient diet [CoCA],Cost of a nutrient adequate diet [CoNA],Cost of a healthy diet [CoHD],Cost of a healthy diet relative to the cost of sufficient energy from starchy staples [CoHD_CoCA],...,Affordability of an energy sufficient diet: ratio of cost to food expenditures [CoCA_fexp],Affordability of a nutrient adequate diet: ratio of cost to food expenditures [CoNA_fexp],Affordability of a healthy diet: ratio of cost to food expenditures [CoHD_fexp],Percent of the population who cannot afford sufficient calories [CoCA_headcount],Percent of the population who cannot afford nutrient adequacy [CoNA_headcount],Percent of the population who cannot afford a healthy diet [CoHD_headcount],Millions of people who cannot afford sufficient calories [CoCA_unafford_n],Millions of people who cannot afford nutrient adequacy [CoNA_unafford_n],Millions of people who cannot afford a healthy diet [CoHD_unafford_n],Population [Pop]
0,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2017.0,YR2017,0.604,1.88,3.476,5.75,...,0.111,0.346,0.64,0,3.2,21.8,0,0.4,2.5,11433438
1,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2018.0,YR2018,..,..,3.559,..,...,..,..,..,..,..,21.2,..,..,2.5,11565203
2,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2019.0,YR2019,..,..,3.628,..,...,..,..,..,..,..,20.8,..,..,2.4,11694721
3,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2020.0,YR2020,..,..,3.639,..,...,..,..,..,..,..,20.3,..,..,2.4,11818618
4,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2021.0,YR2021,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..

(3760, 40)

,Classification Name,Classification Code,Country Name,Country Code,Time,Time Code,Cost of an energy sufficient diet [CoCA],Cost of a nutrient adequate diet [CoNA],Cost of a healthy diet [CoHD],Cost of a healthy diet relative to the cost of sufficient energy from starchy staples [CoHD_CoCA],...,Affordability of an energy sufficient diet: ratio of cost to food expenditures [CoCA_fexp],Affordability of a nutrient adequate diet: ratio of cost to food expenditures [CoNA_fexp],Affordability of a healthy diet: ratio of cost to food expenditures [CoHD_fexp],Percent of the population who cannot afford sufficient calories [CoCA_headcount],Percent of the population who cannot afford nutrient adequacy [CoNA_headcount],Percent of the population who cannot afford a healthy diet [CoHD_headcount],Millions of people who cannot afford sufficient calories [CoCA_unafford_n],Millions of people who cannot afford nutrient adequacy [CoNA_unafford_n],Millions of people who cannot afford a healthy diet [CoHD_unafford_n],Population [Pop]
0,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2017.0,YR2017,0.604,1.88,3.476,5.75,...,0.111,0.346,0.64,0,3.2,21.8,0,0.4,2.5,11433438
1,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2018.0,YR2018,..,..,3.559,..,...,..,..,..,..,..,21.2,..,..,2.5,11565203
2,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2019.0,YR2019,..,..,3.628,..,...,..,..,..,..,..,20.8,..,..,2.4,11694721
3,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2020.0,YR2020,..,..,3.639,..,...,..,..,..,..,..,20.3,..,..,2.4,11818618
4,Food Prices for Nutrition 1.0,FPN 1.0,Tunisia,TUN,2021.0,YR2021,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..

In [17]:
print(data.columns.tolist())
print(series.columns.tolist())

['Classification Name', 'Classification Code', 'Country Name', 'Country Code', 'Time', 'Time Code', 'Cost of an energy sufficient diet [CoCA]', 'Cost of a nutrient adequate diet [CoNA]', 'Cost of a healthy diet [CoHD]', 'Cost of a healthy diet relative to the cost of sufficient energy from starchy staples [CoHD_CoCA]', 'Cost of fruits [CoHD_f]', 'Cost of vegetables [CoHD_v]', 'Cost of starchy staples [CoHD_ss]', 'Cost of animal-source foods [CoHD_asf]', 'Cost of legumes, nuts and seeds [CoHD_lns]', 'Cost of oils and fats [CoHD_of]', 'Cost share for fruits in a least-cost healthy diet [CoHD_f_prop]', 'Cost share for vegetables in a least-cost healthy diet [CoHD_v_prop]', 'Cost share for starchy staples in a least-cost healthy diet [CoHD_ss_prop]', 'Cost share for animal-sourced foods in a least-cost healthy diet [CoHD_asf_prop]', 'Cost share for legumes, nuts and seeds in a least-cost healthy diet [CoHD_lns_prop]', 'Cost share for oils and fats in a least-cost healthy diet [CoHD_of_prop]', 'Cost of fruits relative to the starchy staples in a least-cost healthy diet [CoHD_f_ss]', 'Cost of vegetables relative to the starchy staples in a least-cost healthy diet [CoHD_v_ss]', 'Cost of animal-sourced foods relative to the starchy staples in a least-cost healthy diet [CoHD_asf_ss]', 'Cost of legumes, nuts and seeds relative to the starchy staples in a least-cost healthy diet [CoHD_lns_ss]', 'Cost of oils and fats relative to the starchy staples in a least-cost healthy diet [CoHD_of_ss]', 'Affordability of an energy sufficient diet: ratio of cost to the food poverty line [CoCA_pov]', 'Affordability of a nutrient adequate diet: ratio of cost to the food poverty line [CoNA_pov]', 'Affordability of a healthy diet: ratio of cost to the food poverty line [CoHD_pov]', 'Affordability of an energy sufficient diet: ratio of cost to food expenditures [CoCA_fexp]', 'Affordability of a nutrient adequate diet: ratio of cost to food expenditures [CoNA_fexp]', 'Affordability of a healthy diet: ratio of cost to food expenditures [CoHD_fexp]', 'Percent of the population who cannot afford sufficient calories [CoCA_headcount]', 'Percent of the population who cannot afford nutrient adequacy [CoNA_headcount]', 'Percent of the population who cannot afford a healthy diet [CoHD_headcount]', 'Millions of people who cannot afford sufficient calories [CoCA_unafford_n]', 'Millions of people who cannot afford nutrient adequacy [CoNA_unafford_n]', 'Millions of people who cannot afford a healthy diet [CoHD_unafford_n]', 'Population [Pop]']
['Classification Name', 'Classification Code', 'Country Name', 'Country Code', 'Time', 'Time Code', 'Cost of an energy sufficient diet [CoCA]', 'Cost of a nutrient adequate diet [CoNA]', 'Cost of a healthy diet [CoHD]', 'Cost of a healthy diet relative to the cost of sufficient energy from starchy staples [CoHD_CoCA]', 'Cost of fruits [CoHD_f]', 'Cost of vegetables [CoHD_v]', 'Cost of starchy staples [CoHD_ss]', 'Cost of animal-source foods [CoHD_asf]', 'Cost of legumes, nuts and seeds [CoHD_lns]', 'Cost of oils and fats [CoHD_of]', 'Cost share for fruits in a least-cost healthy diet [CoHD_f_prop]', 'Cost share for vegetables in a least-cost healthy diet [CoHD_v_prop]', 'Cost share for starchy staples in a least-cost healthy diet [CoHD_ss_prop]', 'Cost share for animal-sourced foods in a least-cost healthy diet [CoHD_asf_prop]', 'Cost share for legumes, nuts and seeds in a least-cost healthy diet [CoHD_lns_prop]', 'Cost share for oils and fats in a least-cost healthy diet [CoHD_of_prop]', 'Cost of fruits relative to the starchy staples in a least-cost healthy diet [CoHD_f_ss]', 'Cost of vegetables relative to the starchy staples in a least-cost healthy diet [CoHD_v_ss]', 'Cost of animal-sourced foods relative to the starchy staples in a least-cost healthy diet [CoHD_asf_ss]', 'Cost of legumes, nuts and seeds relative to the starchy staples in a least-cost healthy diet [CoHD_lns_ss]', 'Cost of oils and fats relative to the starchy staples in a least-cost healthy diet [CoHD_of_ss]', 'Affordability of an energy sufficient diet: ratio of cost to the food poverty line [CoCA_pov]', 'Affordability of a nutrient adequate diet: ratio of cost to the food poverty line [CoNA_pov]', 'Affordability of a healthy diet: ratio of cost to the food poverty line [CoHD_pov]', 'Affordability of an energy sufficient diet: ratio of cost to food expenditures [CoCA_fexp]', 'Affordability of a nutrient adequate diet: ratio of cost to food expenditures [CoNA_fexp]', 'Affordability of a healthy diet: ratio of cost to food expenditures [CoHD_fexp]', 'Percent of the population who cannot afford sufficient calories [CoCA_headcount]', 'Percent of the population who cannot afford nutrient adequacy [CoNA_headcount]', 'Percent of the population who cannot afford a healthy diet [CoHD_headcount]', 'Millions of people who cannot afford sufficient calories [CoCA_unafford_n]', 'Millions of people who cannot afford nutrient adequacy [CoNA_unafford_n]', 'Millions of people who cannot afford a healthy diet [CoHD_unafford_n]', 'Population [Pop]']